### ISSUE TITLE
`UltraLogLog::estimate` does not match Algorithm 6

### ISSUE THREAD

**Issue by onalante** [dynatrace-oss/hash4j#153]
There may be two bugs in the normal- and large-range computations
(respectively) of `UltraLogLog::estimate`.

When evaluating the contribution of a register not in the small or large
range, `UltraLogLog::estimate` makes use of the precomputed register
contribution table[^1] (due to equation 14).  There are
$236=4w_{max}-12-4=4(65-p_{min})-16$ values in this table to cover the
range of register values encountered in practice ($p \geq p_{min}=3$).
Importantly, the table does not vary with respect to `p`.  However, when
indexing into `UltraLogLog::REGISTER_CONTRIBUTIONS`, the index is taken
to be $r - 4p-4$[^2], which varies with $p$.  My assumption was that the
index would be $r - 12$ (when $r < 4w$) here.

Meanwhile, in the large-range calculation, it appears that register
values can only contribute to $c_{4w+k,0 \leq k < 4}$ if they are in the
range $[252,256)$[^3].  In contrast to the register contribution table,
(valid) register values for the large-range contribution *do* vary with
$p$; I expected the algorithm to check `r == 4 * (65 - p) + {0,1,2,3}`,
instead of fixed values (seemingly corresponding to $p=2$).

Please let me know if I have misunderstood anything in your paper[^4]
or `UltraLogLog::estimate`.  Thank you for your time.

[^1]: https://github.com/dynatrace-oss/hash4j/blob/fe692fa466b27e0fb44a4fcbe679c4a518892a71/src/main/java/com/dynatrace/hash4j/distinctcount/UltraLogLog.java#L557
[^2]: https://github.com/dynatrace-oss/hash4j/blob/fe692fa466b27e0fb44a4fcbe679c4a518892a71/src/main/java/com/dynatrace/hash4j/distinctcount/UltraLogLog.java#L908
[^3]: https://github.com/dynatrace-oss/hash4j/blob/fe692fa466b27e0fb44a4fcbe679c4a518892a71/src/main/java/com/dynatrace/hash4j/distinctcount/UltraLogLog.java#L917-L920
[^4]: https://arxiv.org/abs/2308.16862

**Comment by oertl** [comment]
Thanks for your feedback!

The hash4j implementation defines the register values slightly differently. As mentioned in the paper in Section 3 ("Practical Implementation"), hash4j uses the transformation `r  <--  r + 4*p - 8` for nonzero register values. This has some advanatages. In particular, the operation `unpack`[^1] can be made branch-free in Java in this case, and the maximum register state is always 255 independent of `p`.

`r - 4*p + 8` would be the corresponding back transformation. As the lookup table only stores the contributions for register values `>= 12`. the lookup index has an offset of 12 resulting in `(r - 4*p + 8) - 12 = r - 4*p - 4` which is exactly what you see here[^2].

The reason why a different definition of the register states was used in the paper was to make the notation simpler. For example, the conversion from UltraLogLog to HyperLogLog described in Section 3.2 ("Compatibility to HyperLogLog") is easier with the definition in the paper.

[^1]: https://github.com/dynatrace-oss/hash4j/blob/fe692fa466b27e0fb44a4fcbe679c4a518892a71/src/main/java/com/dynatrace/hash4j/distinctcount/UltraLogLog.java#L313
[^2]: https://github.com/dynatrace-oss/hash4j/blob/fe692fa466b27e0fb44a4fcbe679c4a518892a71/src/main/java/com/dynatrace/hash4j/distinctcount/UltraLogLog.java#L908

**Comment by onalante** [comment]
Ah, I understand.  I definitely got a bit caught up in Section 2 and
neglected to consult Section 3 when reading through the code.
