### ISSUE TITLE
how to generate long simhash fingerprint use random series

### ISSUE THREAD

**Issue by 1539637481** [dynatrace-oss/hash4j#279]
Hello, the idea of accelerating simhash is brilliant.
Recently I'm optimize my simhash algorithm's performance,but I encounter a problem.
I use simhash in a high-precision requirement scenario, I want to increase the length of the Simhash fingerprint. What method do you use when generating random element hash? I’m using Python and have tried several generation methods, but I haven’t achieved the desired results. I’m curious how you handle this step.

This is the method I use in python:
hash_array = list(bin(random.getrandbits(640))[2:].zfill(640))

**Comment by oertl** [comment]
The element hash is used as seed for a random generator (see https://github.com/dynatrace-oss/hash4j/blob/612480ad22b8229da4db1d1dbfc3fe2ae25d031c/src/main/java/com/dynatrace/hash4j/similarity/SimHashPolicy_v1.java#L59). The sequence of random values is then used for the SimHash computation.

**Comment by 1539637481** [comment]
Thank u! This method quiet improve my simhash algorithm's performance :)
