### ISSUE TITLE
Implement imohash or a similar sampling hash

### ISSUE THREAD

**Issue by mrgreywater** [dynatrace-oss/hash4j#80]
**Is your feature request related to a problem? Please describe.**
When comparing large files for duplicates, usual hashing algorithms are limited by the speed of which the full file content can be read. This starts to be a problem when hashing large files. By only hashing parts of the data and its size you don't have to read all the data but get a hash that can indicate duplicates with sufficient confidence.

**Describe the solution you'd like**
Implement imohash or a similar sampling hash algorithm.

**Describe alternatives you've considered**
Implementing it on top of hash4j.

**Comment by oertl** [comment]
@mrgreywater The Imohash algorithm would be very easy to implement. However, I am not quite sure what a useful and generic interface should look like. Do you have a suggestion?

**Comment by mrgreywater** [comment]
I thought something like this, even though this implementation currently doesn't match the reference implementation in its output. Probably some seed or little/big endian mismatch. Didn't do much debugging.

```java
package com.dynatrace.hash4j.sampling;

import com.dynatrace.hash4j.hashing.HashValue128;
import com.dynatrace.hash4j.hashing.Hashing;

import java.io.EOFException;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

public class Imohash {
    private long sampleThreshold = 128 * 1024;
    private int sampleSize = 16 * 1024;

    public HashValue128 hashFile(File file) throws IOException {
        return hashFile(file.toPath());
    }
    
    public HashValue128 hashFile(Path path) throws IOException {
        try (InputStream fileContent = Files.newInputStream(path, StandardOpenOption.READ)) {
            return hashInputStream(fileContent, Files.size(path));
        }
    }
    
    public HashValue128 hashInputStream(InputStream stream) throws IOException {
        long length = stream.skip(Long.MAX_VALUE);
        stream.reset();
        return hashInputStream(stream, length);
    }
    
    public HashValue128 hashInputStream(InputStream stream, long length) throws IOException {
        assert (sampleSize * 4L < sampleThreshold);
        var hashStream = Hashing.murmur3_128().hashStream();
        if (length < sampleThreshold || sampleSize < 1) {
            hashStream.putByteArray(stream.readAllBytes());
        } else {
            long toSkip = 0;
            byte[] buf = new byte[sampleSize];

            long pos = stream.read(buf);
            hashStream.putByteArray(buf);

            toSkip = length / 2 - pos;
            skipNBytes(stream, toSkip);
            pos += toSkip + stream.read(buf);
            hashStream.putByteArray(buf);

            toSkip = length - sampleSize - pos;
            skipNBytes(stream, toSkip);
            pos += toSkip + stream.read(buf);
            hashStream.putByteArray(buf);
        }

        var result = hashStream.get().toByteArray();
        encodeVarint(result, length);
        var mostSignificantBytes = ByteBuffer.wrap(result, 8, 8).getLong();
        var leastSignificantBytes = ByteBuffer.wrap(result).getLong();
        return new HashValue128(mostSignificantBytes, leastSignificantBytes);
    }

    public int getSampleSize() {
        return sampleSize;
    }

    public void setSampleSize(int sampleSize) {
        this.sampleSize = sampleSize;
    }

    public long getSampleThreshold() {
        return sampleThreshold;
    }

    public void setSampleThreshold(long sampleThreshold) {
        this.sampleThreshold = sampleThreshold;
    }

    private void encodeVarint(byte[] buf, long x) {
        int i = 0;
        while (x >= 0x80) {
            buf[i] = (byte) ((byte)x | 0x80);
            x >>= 7;
            i++;
        }
        buf[i] = (byte)x;
    }

    // InputStream::skipNBytes() since JDK12
    private void skipNBytes(InputStream s, long n) throws IOException {
        long remaining = n;
        while (remaining > 0) {
            long skipped = s.skip(remaining);
            if (skipped == 0) {
                if (s.read() < 0) {
                    throw new EOFException();
                }
                remaining--;
            } else if (skipped <= remaining) {
                remaining -= skipped;
            } else {
                throw new IOException("Unable to skip exactly.");
            }
        }
    }
}
```

**Comment by oertl** [comment]
It seems that the Go implementation of Murmur3 used by Imohash returns the bytes of the hash in reverse order compared to the C reference implementation (https://github.com/aappleby/smhasher), Guava, and hash4j. To achieve compatibility with Imohash, the byte sequence needs to be reversed.

**Comment by mrgreywater** [comment]
The string output of the implementation of Imohash::hashInputStream().toString() matches the string output of the hash returned by the imohash.go reference implementation.

**Comment by oertl** [comment]
@mrgreywater I have created PR https://github.com/dynatrace-oss/hash4j/pull/85 based on your proposal, please hava a look

**Comment by mrgreywater** [comment]
It looks great! I haven't checked the accuracy of the resulting hashes, but I'm sure you verified your tests against the reference implementation. Especially for very large hashes that overflow the first 64Bits in the now optimized varUInt encoding.
I really appreciate it.

**Comment by oertl** [comment]
>  Especially for very large hashes that overflow the first 64Bits in the now optimized varUInt encoding.
Testing very long input against the reference Go implementation is still something I would like to improve. Unfortunately, I am an absolute Go beginner, and would need some help to mock the SectionReader.
