### ISSUE TITLE
Request to publish JMH results

### ISSUE THREAD

**Issue by carl-mastrangelo** [dynatrace-oss/hash4j#91]
I'm interested in seeing (roughly) how fast Hash4J's hash functions are, and possibly how fast the comparable Guava/OpenHFT functions are too.  I could run these on my own machine, but it would be nice as a quick approximation of what kind of performance numbers are reasonable.  

In particular, the blog post describing the need for Hash4J mentions exact compatibility with the reference C++ implementation.  I'm curious if the compatibility comes at a noticeable cost compared to the alternative implementations?

**Comment by oertl** [comment]
[Here](https://gist.github.com/oertl/eabe74a8cc6495ce574f1c2b25350164) are some latest Hash4j benchmark results for f18ed4f7f78c1038f437d2e491daef9bac005898 on a Dell Precision 5560 running Windows and Turbo Boost Mode switched off.

The compatibility with Murmur3_128 does not really involve additional costs. See https://github.com/google/guava/issues/3493, a fix would only require two AND operations. The only reason this is not fixed there is their own compatibility.

**Comment by carl-mastrangelo** [comment]
Thank you much for providing this data and explanation!

**Comment by oertl** [comment]
We have created the [hash4j-benchmarks](https://github.com/dynatrace-oss/hash4j-benchmarks) repository which collects benchmark results for hash4j.
